package frc.robot.subsystems;

import frc.robot.Constants;
import frc.lib.telemetry.SubsystemTelemetry;
import frc.lib.monitors.RobotHealthMonitor;
import edu.wpi.first.wpilibj.RobotBase;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.controls.PositionVoltage;
import com.ctre.phoenix6.controls.Follower;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.signals.ForwardLimitTypeValue;
import com.ctre.phoenix6.signals.ReverseLimitTypeValue;
import com.ctre.phoenix6.signals.ForwardLimitValue;
import com.ctre.phoenix6.signals.ReverseLimitValue;

/**
 * ElevatorSubsystem — generated by 3544 FRC Code Generator.
 *
 * Motor   : Kraken X60 (TalonFX)
 * Encoder : Integrated (motor)
 * Ratios  : Motor→Encoder 1.0:1  |  Motor→Mechanism 12.0:1
 * Control : position   States: ready, atHome, fault, homing, L1, L2, L3, L4
 * CAN bus  : default (rio)
 *   Reverse limit: enabled (auto-zero)
 *
 * Motors:
 *   LeaderMotor (CAN 30) [leader]
 *   FollowerMotor (CAN 31) [follower]
 *
 * Freely edit: onEnterState(), onExitState(), setTarget*(), setOutput().
 * Do not remove the telemetry.publish() call in periodic().
 */
/* 3544-GENERATOR-CONFIG
{
  "can_bus": "",
  "cancoder_id": 0,
  "encoder_type": "integrated",
  "limit_fwd": {
    "enabled": false,
    "normally_open": false
  },
  "limit_rev": {
    "auto_zero": true,
    "enabled": true,
    "normally_open": true
  },
  "mode": "position",
  "motor_to_encoder_ratio": 1.0,
  "motor_to_mech_ratio": 12.0,
  "motor_type": "kraken_x60",
  "motors": [
    {
      "can_id": 30,
      "inverted": true,
      "name": "LeaderMotor",
      "pdh_ch": 13
    },
    {
      "can_id": 31,
      "inverted": false,
      "name": "FollowerMotor",
      "pdh_ch": 12
    }
  ],
  "name": "Elevator",
  "states": [
    "ready",
    "atHome",
    "fault",
    "homing",
    "L1",
    "L2",
    "L3",
    "L4"
  ],
  "tunables": [
    {
      "default": 0.2,
      "key": "kP",
      "label": "kP",
      "step": 0.01
    },
    {
      "default": 21.0,
      "key": "gfggre",
      "label": "432rr2",
      "step": 0.01
    }
  ]
}
*/
public class ElevatorSubsystem {

    // ─── Constants ───────────────────────────────────────────────────────────────
    // Hardware IDs, ratios, states, and tunable defaults live in Constants.Elevator.

    // ─── Hardware ─────────────────────────────────────────────────────────────
    private final TalonFX leaderMotor;
    private final TalonFX followerMotor;
    private final PositionVoltage positionRequest = new PositionVoltage(0);

    // ─── State ────────────────────────────────────────────────────────────────
    private double measuredPosition = 0.0; // degrees
    private double targetPositionDeg = 0.0;
    private double simPosition      = 0.0;
    private boolean ready        = false;
    private String  currentState = Constants.Elevator.STATES[0];
    private String  fault        = "";
    private String  warning      = "";

    // ─── Telemetry ────────────────────────────────────────────────────────────────
    private final SubsystemTelemetry telemetry;

    // ─── Constructor ─────────────────────────────────────────────────────────────
    public ElevatorSubsystem() {
        leaderMotor = new TalonFX(Constants.Elevator.LEADER_MOTOR_CAN_ID);
        var motorConfig = new TalonFXConfiguration();
        motorConfig.MotorOutput.Inverted = Constants.Elevator.LEADER_MOTOR_INVERTED ? InvertedValue.Clockwise_Positive : InvertedValue.CounterClockwise_Positive;
        motorConfig.Feedback.SensorToMechanismRatio = Constants.Elevator.MOTOR_TO_MECH_RATIO;
        motorConfig.Slot0.kP = Constants.Elevator.K_P_DEFAULT;
        motorConfig.HardwareLimitSwitch.ReverseLimitEnable = true;
        motorConfig.HardwareLimitSwitch.ReverseLimitType   = ReverseLimitTypeValue.NormallyOpen;
        motorConfig.HardwareLimitSwitch.ReverseLimitAutosetPositionEnable = true;
        motorConfig.HardwareLimitSwitch.ReverseLimitAutosetPositionValue  = 0.0;
        leaderMotor.getConfigurator().apply(motorConfig);
        followerMotor = new TalonFX(Constants.Elevator.FOLLOWER_MOTOR_CAN_ID);
        followerMotor.setControl(new Follower(Constants.Elevator.LEADER_MOTOR_CAN_ID, Constants.Elevator.FOLLOWER_MOTOR_INVERTED ? MotorAlignmentValue.Opposed : MotorAlignmentValue.Aligned));

        telemetry = new SubsystemTelemetry(Constants.Elevator.SUBSYSTEM_NAME, Constants.Elevator.CONTROL_MODE);
        telemetry.registerTunable("kP", Constants.Elevator.K_P_DEFAULT);
        telemetry.registerTunable("gfggre", Constants.Elevator.GFGGRE_DEFAULT);
    }

    // ─── Periodic ────────────────────────────────────────────────────────────────
    public void periodic() {
        // ── Live tunables ────────────────────────────────────────────────────────
        double kP = telemetry.getTunable("kP", Constants.Elevator.K_P_DEFAULT);
        double gfggre = telemetry.getTunable("gfggre", Constants.Elevator.GFGGRE_DEFAULT);

        var slot0 = new Slot0Configs();
        slot0.kP = kP;
        leaderMotor.getConfigurator().apply(slot0);

        // ── Sensors ──────────────────────────────────────────────────────────────
        if (RobotBase.isReal()) {
            measuredPosition = leaderMotor.getPosition().getValueAsDouble() * 360.0;
        } else {
            simPosition += (targetPositionDeg - simPosition) * kP;
            measuredPosition = simPosition;
        }
        ready   = Math.abs(targetPositionDeg - measuredPosition) < 2.0;
        warning = (Math.abs(targetPositionDeg - measuredPosition) > 10.0) ? "Elevator: not at target" : "";

        telemetry.publish(measuredPosition, targetPositionDeg, ready, currentState, fault, warning);
    }

    public void simulationPeriodic() { /* periodic() handles both real and sim */ }

    public void registerHealthDevices(RobotHealthMonitor health) {
        health.registerTalonFX(
            Constants.Elevator.SUBSYSTEM_NAME,
            "LeaderMotor",
            Constants.Elevator.LEADER_MOTOR_CAN_ID,
            Constants.Elevator.CAN_BUS,
            leaderMotor
        );
        health.registerTalonFX(
            Constants.Elevator.SUBSYSTEM_NAME,
            "FollowerMotor",
            Constants.Elevator.FOLLOWER_MOTOR_CAN_ID,
            Constants.Elevator.CAN_BUS,
            followerMotor
        );
    }

    // ─── Control API ──────────────────────────────────────────────────────────
    /** Command target position in degrees. */
    public void setTargetPosition(double degrees) {
        targetPositionDeg = degrees;
        if (RobotBase.isReal()) leaderMotor.setControl(positionRequest.withPosition(degrees / 360.0));
    }
    public double getPosition()       { return measuredPosition; }
    public boolean isAtReverseLimit() { return RobotBase.isReal() && leaderMotor.getReverseLimit().getValue() == ReverseLimitValue.ClosedToGround; }

    /** Runs the generated self-test movement. TODO: tune the movement to match real mechanism limits. */
    public void runSelfTest(double value) {
        setTargetPosition(value);
    }

    /** Stops any generated self-test movement. */
    public void stopSelfTest() {
        setTargetPosition(measuredPosition);
    }

    /** Supply current from this subsystem's generated motors (A). */
    public double getSupplyCurrentA() {
        if (RobotBase.isReal()) return leaderMotor.getSupplyCurrent().refresh(false).getValueAsDouble() + followerMotor.getSupplyCurrent().refresh(false).getValueAsDouble();
        return Math.min(12.0, Math.abs(targetPositionDeg - measuredPosition) * 0.5 + 2.0);
    }

    /** Highest generated motor controller temperature (C). */
    public double getTemperatureC() {
        if (RobotBase.isReal()) return Math.max(leaderMotor.getDeviceTemp().refresh(false).getValueAsDouble(), followerMotor.getDeviceTemp().refresh(false).getValueAsDouble());
        return 25.0;
    }

    // ─── State Machine ───────────────────────────────────────────────────────────
    // Valid states: 'ready', 'atHome', 'fault', 'homing', 'L1', 'L2', 'L3', 'L4'
    public void setState(String newState) {
        if (newState.equals(currentState)) return;
        onExitState(currentState);
        currentState = newState;
        onEnterState(newState);
    }

    private void onEnterState(String state) {
        switch (state) {
            case "ready":
                // Add state-specific commands for "ready" here.
                break;
            case "atHome":
                // Add state-specific commands for "atHome" here.
                break;
            case "fault":
                // Add state-specific commands for "fault" here.
                break;
            case "homing":
                // Add state-specific commands for "homing" here.
                break;
            case "L1":
                // Add state-specific commands for "L1" here.
                break;
            case "L2":
                // Add state-specific commands for "L2" here.
                break;
            case "L3":
                // Add state-specific commands for "L3" here.
                break;
            case "L4":
                // Add state-specific commands for "L4" here.
                break;
            default: break;
        }
    }

    private void onExitState(String state) { /* cleanup on state exit */ }

    public String  getState()   { return currentState; }
    public boolean isReady()    { return ready; }
    public String  getFault()   { return fault; }
    public String  getWarning() { return warning; }
}
