package frc.robot.subsystems;

import frc.robot.Constants;
import frc.robot.SubsystemTelemetry;
import edu.wpi.first.wpilibj.RobotBase;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.controls.VelocityVoltage;
import com.ctre.phoenix6.configs.Slot0Configs;

/**
 * SpindexerHookSubsystem — generated by 3544 FRC Code Generator.
 *
 * Motor   : Kraken X44 (TalonFX)
 * Encoder : Integrated (motor)
 * Ratios  : Motor→Encoder 1.0:1  |  Motor→Mechanism 12.0:1
 * Control : velocity   States: ready, running, unjamming, fault
 * CAN bus  : default (rio)
 *
 * Motors:
 *   LeaderMotor (CAN 20) [leader]
 *
 * Freely edit: onEnterState(), onExitState(), setTarget*(), setOutput().
 * Do not remove the telemetry.publish() call in periodic().
 */
/* 3544-GENERATOR-CONFIG
{
  "can_bus": "",
  "cancoder_id": 0,
  "encoder_type": "integrated",
  "limit_fwd": {
    "enabled": false,
    "normally_open": true
  },
  "limit_rev": {
    "auto_zero": true,
    "enabled": false,
    "normally_open": true
  },
  "mode": "velocity",
  "motor_to_encoder_ratio": 1.0,
  "motor_to_mech_ratio": 12.0,
  "motor_type": "kraken_x44",
  "motors": [
    {
      "can_id": 20,
      "inverted": false,
      "name": "LeaderMotor",
      "pdh_ch": 2
    }
  ],
  "name": "SpindexerHook",
  "states": [
    "ready",
    "running",
    "unjamming",
    "fault"
  ],
  "tunables": [
    {
      "default": 0.005,
      "key": "kP",
      "label": "kP",
      "step": 0.001
    },
    {
      "default": 0.00018,
      "key": "kV",
      "label": "kV (ff)",
      "step": 0.0001
    },
    {
      "default": 250.0,
      "key": "TargetRPM",
      "label": "Target RPM",
      "step": 50.0
    }
  ]
}
*/
public class SpindexerHookSubsystem {

    // ─── Constants ───────────────────────────────────────────────────────────────
    // Hardware IDs, ratios, states, and tunable defaults live in Constants.SpindexerHook.

    // ─── Hardware ─────────────────────────────────────────────────────────────
    private final TalonFX leaderMotor;
    private final VelocityVoltage velocityRequest = new VelocityVoltage(0);

    // ─── State ────────────────────────────────────────────────────────────────
    private double measuredVelocity = 0.0; // RPM
    private double simVelocity       = 0.0;
    private boolean ready        = false;
    private String  currentState = Constants.SpindexerHook.STATES[0];
    private String  fault        = "";
    private String  warning      = "";

    // ─── Telemetry ────────────────────────────────────────────────────────────────
    private final SubsystemTelemetry telemetry;

    // ─── Constructor ─────────────────────────────────────────────────────────────
    public SpindexerHookSubsystem() {
        leaderMotor = new TalonFX(Constants.SpindexerHook.LEADER_MOTOR_CAN_ID);
        var motorConfig = new TalonFXConfiguration();
        motorConfig.MotorOutput.Inverted = Constants.SpindexerHook.LEADER_MOTOR_INVERTED ? InvertedValue.Clockwise_Positive : InvertedValue.CounterClockwise_Positive;
        motorConfig.Feedback.SensorToMechanismRatio = Constants.SpindexerHook.MOTOR_TO_MECH_RATIO;
        motorConfig.Slot0.kP = Constants.SpindexerHook.K_P_DEFAULT;
        motorConfig.Slot0.kV = Constants.SpindexerHook.K_V_DEFAULT;
        leaderMotor.getConfigurator().apply(motorConfig);

        telemetry = new SubsystemTelemetry(Constants.SpindexerHook.SUBSYSTEM_NAME, Constants.SpindexerHook.CONTROL_MODE);
        telemetry.registerTunable("kP", Constants.SpindexerHook.K_P_DEFAULT);
        telemetry.registerTunable("kV", Constants.SpindexerHook.K_V_DEFAULT);
        telemetry.registerTunable("TargetRPM", Constants.SpindexerHook.TARGET_RPM_DEFAULT);
    }

    // ─── Periodic ────────────────────────────────────────────────────────────────
    public void periodic() {
        // ── Live tunables ────────────────────────────────────────────────────────
        double kP = telemetry.getTunable("kP", Constants.SpindexerHook.K_P_DEFAULT);
        double kV = telemetry.getTunable("kV", Constants.SpindexerHook.K_V_DEFAULT);
        double targetRPM = telemetry.getTunable("TargetRPM", Constants.SpindexerHook.TARGET_RPM_DEFAULT);

        var slot0 = new Slot0Configs();
        slot0.kP = kP;
        slot0.kV = kV;
        leaderMotor.getConfigurator().apply(slot0);

        // ── Sensors ──────────────────────────────────────────────────────────────
        if (RobotBase.isReal()) {
            measuredVelocity = leaderMotor.getVelocity().getValueAsDouble() * 60.0;
        } else {
            double err = targetRPM - simVelocity;
            simVelocity += err * kP * 50.0 + targetRPM * kV;
            simVelocity  = Math.max(0, simVelocity);
            measuredVelocity = simVelocity;
        }
        ready   = Math.abs(targetRPM - measuredVelocity) < 50.0;
        warning = (Math.abs(targetRPM - measuredVelocity) > 200 && measuredVelocity > 50) ? "SpindexerHook: not at target" : "";

        telemetry.publish(measuredVelocity, targetRPM, ready, currentState, fault, warning);
    }

    public void simulationPeriodic() { /* periodic() handles both real and sim */ }

    // ─── Control API ──────────────────────────────────────────────────────────
    /** Command target velocity in RPM. */
    public void setTargetVelocity(double rpm) {
        if (RobotBase.isReal()) leaderMotor.setControl(velocityRequest.withVelocity(rpm / 60.0));
    }
    public double getVelocity()       { return measuredVelocity; }

    // ─── State Machine ───────────────────────────────────────────────────────────
    // Valid states: 'ready', 'running', 'unjamming', 'fault'
    public void setState(String newState) {
        if (newState.equals(currentState)) return;
        onExitState(currentState);
        currentState = newState;
        onEnterState(newState);
    }

    private void onEnterState(String state) {
        switch (state) {
            case "ready":
                // TODO: command motors for "ready"
                break;
            case "running":
                // TODO: command motors for "running"
                break;
            case "unjamming":
                // TODO: command motors for "unjamming"
                break;
            case "fault":
                // TODO: command motors for "fault"
                break;
            default: break;
        }
    }

    private void onExitState(String state) { /* cleanup on state exit */ }

    public String  getState()   { return currentState; }
    public boolean isReady()    { return ready; }
    public String  getFault()   { return fault; }
    public String  getWarning() { return warning; }
}
