package frc.robot.subsystems;

import frc.robot.Constants;
import frc.lib.telemetry.SubsystemTelemetry;
import frc.lib.monitors.RobotHealthMonitor;
import edu.wpi.first.wpilibj.RobotBase;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.controls.DutyCycleOut;

/**
 * SpindexerFeedSubsystem — generated by 3544 FRC Code Generator.
 *
 * Motor   : Kraken X44 (TalonFX)
 * Encoder : Integrated (motor)
 * Ratios  : Motor→Encoder 1.0:1  |  Motor→Mechanism 3.0:1
 * Control : open_loop   States: ready, running, fault
 * CAN bus  : default (rio)
 *
 * Motors:
 *   LeaderMotor (CAN 21) [leader]
 *
 * Freely edit: onEnterState(), onExitState(), setTarget*(), setOutput().
 * Do not remove the telemetry.publish() call in periodic().
 */
/* 3544-GENERATOR-CONFIG
{
  "can_bus": "",
  "cancoder_id": 0,
  "encoder_type": "integrated",
  "limit_fwd": {
    "enabled": false,
    "normally_open": true
  },
  "limit_rev": {
    "auto_zero": true,
    "enabled": false,
    "normally_open": true
  },
  "mode": "open_loop",
  "motor_to_encoder_ratio": 1.0,
  "motor_to_mech_ratio": 3.0,
  "motor_type": "kraken_x44",
  "motors": [
    {
      "can_id": 21,
      "inverted": false,
      "name": "LeaderMotor",
      "pdh_ch": 3
    }
  ],
  "name": "SpindexerFeed",
  "states": [
    "ready",
    "running",
    "fault"
  ],
  "tunables": [
    {
      "default": 1.0,
      "key": "feedSpeed",
      "label": "feedSpeed",
      "step": 0.1
    }
  ]
}
*/
public class SpindexerFeedSubsystem {

    // ─── Constants ───────────────────────────────────────────────────────────────
    // Hardware IDs, ratios, states, and tunable defaults live in Constants.SpindexerFeed.

    // ─── Hardware ─────────────────────────────────────────────────────────────
    private final TalonFX leaderMotor;
    private final DutyCycleOut dutyCycleRequest = new DutyCycleOut(0);

    // ─── State ────────────────────────────────────────────────────────────────
    private double outputPercent = 0.0;
    private boolean ready        = true;
    private String  currentState = Constants.SpindexerFeed.STATES[0];
    private String  fault        = "";
    private String  warning      = "";

    // ─── Telemetry ────────────────────────────────────────────────────────────────
    private final SubsystemTelemetry telemetry;

    // ─── Constructor ─────────────────────────────────────────────────────────────
    public SpindexerFeedSubsystem() {
        leaderMotor = new TalonFX(Constants.SpindexerFeed.LEADER_MOTOR_CAN_ID);
        var motorConfig = new TalonFXConfiguration();
        motorConfig.MotorOutput.Inverted = Constants.SpindexerFeed.LEADER_MOTOR_INVERTED ? InvertedValue.Clockwise_Positive : InvertedValue.CounterClockwise_Positive;
        motorConfig.Feedback.SensorToMechanismRatio = Constants.SpindexerFeed.MOTOR_TO_MECH_RATIO;
        leaderMotor.getConfigurator().apply(motorConfig);

        telemetry = new SubsystemTelemetry(Constants.SpindexerFeed.SUBSYSTEM_NAME, Constants.SpindexerFeed.CONTROL_MODE);
        telemetry.registerTunable("feedSpeed", Constants.SpindexerFeed.FEED_SPEED_DEFAULT);
    }

    // ─── Periodic ────────────────────────────────────────────────────────────────
    public void periodic() {
        // ── Live tunables ────────────────────────────────────────────────────────
        double feedSpeed = telemetry.getTunable("feedSpeed", Constants.SpindexerFeed.FEED_SPEED_DEFAULT);

        // ── Sensors ──────────────────────────────────────────────────────────────
        // open-loop — no sensor feedback

        telemetry.publish(outputPercent, 0, ready, currentState, fault, warning);
    }

    public void simulationPeriodic() { /* periodic() handles both real and sim */ }

    public void registerHealthDevices(RobotHealthMonitor health) {
        health.registerTalonFX(
            Constants.SpindexerFeed.SUBSYSTEM_NAME,
            "LeaderMotor",
            Constants.SpindexerFeed.LEADER_MOTOR_CAN_ID,
            Constants.SpindexerFeed.CAN_BUS,
            leaderMotor
        );
    }

    // ─── Control API ──────────────────────────────────────────────────────────
    /** Set open-loop output (-1 to 1). */
    public void setOutput(double percent) {
        outputPercent = Math.max(-1.0, Math.min(1.0, percent));
        if (RobotBase.isReal()) leaderMotor.setControl(dutyCycleRequest.withOutput(outputPercent));
    }
    public double getOutput() { return outputPercent; }

    /** Runs the generated self-test movement. TODO: tune the movement to match real mechanism limits. */
    public void runSelfTest(double value) {
        setOutput(value);
    }

    /** Stops any generated self-test movement. */
    public void stopSelfTest() {
        setOutput(0.0);
    }

    /** Supply current from this subsystem's generated motors (A). */
    public double getSupplyCurrentA() {
        if (RobotBase.isReal()) return leaderMotor.getSupplyCurrent().refresh(false).getValueAsDouble();
        return Math.abs(outputPercent) * 14.0;
    }

    /** Highest generated motor controller temperature (C). */
    public double getTemperatureC() {
        if (RobotBase.isReal()) return leaderMotor.getDeviceTemp().refresh(false).getValueAsDouble();
        return 25.0;
    }

    // ─── State Machine ───────────────────────────────────────────────────────────
    // Valid states: 'ready', 'running', 'fault'
    public void setState(String newState) {
        if (newState.equals(currentState)) return;
        onExitState(currentState);
        currentState = newState;
        onEnterState(newState);
    }

    private void onEnterState(String state) {
        switch (state) {
            case "ready":
                // Add state-specific commands for "ready" here.
                break;
            case "running":
                // Add state-specific commands for "running" here.
                break;
            case "fault":
                // Add state-specific commands for "fault" here.
                break;
            default: break;
        }
    }

    private void onExitState(String state) { /* cleanup on state exit */ }

    public String  getState()   { return currentState; }
    public boolean isReady()    { return ready; }
    public String  getFault()   { return fault; }
    public String  getWarning() { return warning; }
}
